package Internal;

import Controller.ProjetoController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Usuario;

public class CadastrarProjeto extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroProjeto
     */
    private Usuario usuarioLogado;
    
    public CadastrarProjeto(Usuario usuarioLogado) {
        initComponents();
        this.usuarioLogado = usuarioLogado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formularioDeProjeto = new javax.swing.JPanel();
        labelCadastroDeProjeto = new javax.swing.JLabel();
        labelNomProjeto = new javax.swing.JLabel();
        fieldNomeProjeto = new javax.swing.JTextField();
        buttonVoltar = new javax.swing.JButton();
        buttounSalvar = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        descricaoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoCadastroProjeto = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        formularioDeProjeto.setBackground(new java.awt.Color(255, 255, 255));

        labelCadastroDeProjeto.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelCadastroDeProjeto.setText("Cadastrar Projeto");

        labelNomProjeto.setText("Nome Projeto");

        buttonVoltar.setBackground(new java.awt.Color(0, 204, 255));
        buttonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        buttounSalvar.setBackground(new java.awt.Color(0, 204, 255));
        buttounSalvar.setForeground(new java.awt.Color(255, 255, 255));
        buttounSalvar.setText("Salvar");
        buttounSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttounSalvarMouseClicked(evt);
            }
        });
        buttounSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttounSalvarActionPerformed(evt);
            }
        });

        buttonLimpar.setBackground(new java.awt.Color(0, 204, 255));
        buttonLimpar.setForeground(new java.awt.Color(255, 255, 255));
        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        descricaoLabel.setText("Descrição");

        textoCadastroProjeto.setColumns(20);
        textoCadastroProjeto.setRows(5);
        jScrollPane1.setViewportView(textoCadastroProjeto);

        javax.swing.GroupLayout formularioDeProjetoLayout = new javax.swing.GroupLayout(formularioDeProjeto);
        formularioDeProjeto.setLayout(formularioDeProjetoLayout);
        formularioDeProjetoLayout.setHorizontalGroup(
            formularioDeProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioDeProjetoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(formularioDeProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formularioDeProjetoLayout.createSequentialGroup()
                        .addComponent(labelNomProjeto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formularioDeProjetoLayout.createSequentialGroup()
                        .addGroup(formularioDeProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(fieldNomeProjeto)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formularioDeProjetoLayout.createSequentialGroup()
                                .addComponent(descricaoLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formularioDeProjetoLayout.createSequentialGroup()
                                .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(buttounSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(buttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
            .addGroup(formularioDeProjetoLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(labelCadastroDeProjeto)
                .addGap(0, 142, Short.MAX_VALUE))
        );
        formularioDeProjetoLayout.setVerticalGroup(
            formularioDeProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioDeProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastroDeProjeto)
                .addGap(5, 5, 5)
                .addComponent(labelNomProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(descricaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formularioDeProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttounSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formularioDeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formularioDeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttounSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttounSalvarActionPerformed
       ProjetoController projeto = new ProjetoController( this.fieldNomeProjeto.getText(),this.textoCadastroProjeto.getText(), usuarioLogado.getIdUsuario());
        try {
            projeto.salvarProjeto();
            System.out.println("Projeto Criado e Salvo");
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarProjeto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttounSalvarActionPerformed

    private void buttounSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttounSalvarMouseClicked

    }//GEN-LAST:event_buttounSalvarMouseClicked

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        this.fieldNomeProjeto.setText("");
        this.textoCadastroProjeto.setText("");
    }//GEN-LAST:event_buttonLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JButton buttounSalvar;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JTextField fieldNomeProjeto;
    private javax.swing.JPanel formularioDeProjeto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCadastroDeProjeto;
    private javax.swing.JLabel labelNomProjeto;
    private javax.swing.JTextArea textoCadastroProjeto;
    // End of variables declaration//GEN-END:variables
}
